name: 'Get an environment public key'
description: 'Get the public key for an environment, which you need to encrypt environment secrets. You need to encrypt a secret before you can create or update secrets.'
author: 'Tobiriz'
inputs:
  token:
    description: 'GitHub access token for authorization.'
    required: true
  githubApi:
    description: 'URL of the REST-API of your organization.'
    default: 'https://api.github.com'
  repositoryId:
    description: 'The unique identifier of the repository.'
    required: true
  environmentName:
    description: 'The name of the environment.'
    required: true
outputs:
  key:
    description: 'Public key for an environment, which you need to encrypt environment secrets.'
  keyId:
    description: 'Public key ID, which you need to save a secret.'
runs:
  using: 'node20'
  main: index.js
