name: 'List organization secrets'
description: 'Lists all secrets available in an organization without revealing their encrypted values.'
author: 'Tobiriz'
inputs:
  token:
    description: 'GitHub access token with the admin:org scope.'
    required: true
  organization:
    description: 'The organization name. The name is not case sensitive.'
    required: true
  githubApi:
    description: 'REST-API URL of your organization.'
    default: 'https://api.github.com'
  resultsPerPage:
    description: 'The number of results per page (max 100).'
    default: '30'
  page:
    description: 'Page number of the results to fetch.'
    default: '1'
runs:
  using: composite
  steps:
    - name: 'Run script'
      shell: bash
      run: >
        ./script.sh
        '${{ inputs.token }}'
        '${{ inputs.organization }}'
        '${{ inputs.githubApi }}'
        '${{ inputs.resultsPerPage }}'
        '${{ inputs.page }}'
